name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download run-clang-format
      run: git submodule update --init run-clang-format

    - name: Test
      run: ./scripts/test-all.sh

    - name: Check code formatting
      run: ./scripts/check-fmt.sh

  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt install doxygen graphviz

      - name: Build the docs
        run: ./scripts/docs.sh

      - name: Deploy the docs
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs/
